// import * as mongoose from 'mongoose';

// export const MasterSourceDemandDeliverySchema = new mongoose.Schema({
//   // _id: String,
//   // value: String,
//   // name: String,
//   // rowOrder: Number,
//   // createBy: String,
//   // createDate: Date,
//   // updateBy: String,
//   // updateDate: Date,
//   _id: String,
//   value: String,
//   product: String,
//   unit: String,
//   source: String,
//   demand: String,
//   deliveryPoint: String,
//   remark: String,
//   activeStatus: String,
//   rowOrder: Number,
//   createBy: String,
//   createDate: Date,
//   updateBy: String,
//   updateDate: Date,
// });
