// import * as mongoose from 'mongoose';

// export const ReferencePriceVersionSchema = new mongoose.Schema({
//   _id: String,
//   year: Number,
//   action: String,
//   unit: String,
//   remark: String,
//   activeStatus: String,
//   refPriceNameFrom: String,
//   refPriceNameTo: String,
//   version: Number,
//   versionName:String,
//   filePath: String,
//   fileName:String,
//   filePath1: String,
//   fileName1: String,
//   filePath2: String,
//   fileName2: String,
//   filePath3: String,
//   fileName3: String,
//   rowOrder: Number,
//   createBy: String,
//   createDate: Date,
//   updateBy: String,
//   updateDate: Date,
// });
